### ISSUE TITLE
unable to run example code

### ISSUE THREAD

**Issue by DavidNovikov** [lanl/scico#553] opened 2024-09-19 10:19 UTC
Hi I have installed the scico package with pip in google colab and run into the following issue when I try to run it.

here is the link to the colab page that I am using

https://colab.research.google.com/drive/16YdnXTKYFMZQthMqpZq84jlszEOzKsII?usp=sharing

I believe it is because scipy has deprecated linalg.tril
https://docs.scipy.org/doc/scipy-1.12.0/reference/generated/scipy.linalg.tril.html

Is it possible to bump the version of Jax to something more recent?

**Comment by wardahub-design** [comment] 2024-09-19 10:20
try this
https://mega.co.nz/#!B31G2LaZ!uBBOCp9hLC7bq9kP8NC6s4DanQJJZuoFRr5FI_jkeic

you may need to install the c compiler

**Comment by bwohlberg** [comment] 2024-09-19 13:22
The colab link you provided is not accessible. The problem is indeed probably due to the older version of JAX in the dependencies for scico 0.0.5 available from pypi and conda. The development version of scico on github currently supports jax versions up to 0.4.31. When installing scico on colab, I suggest using
```
!pip install git+https://github.com/lanl/scico
```
to install the development version, as in the example notebooks accessible via the Open in Colab badge on the main scico github page.

**Comment by DavidNovikov** [comment] 2024-09-19 13:27
Thank you, I will use the development version for now! Do you know when the next version of scico will be published?

**Comment by bwohlberg** [comment] 2024-09-19 13:35
Please report back once you have tried it and confirmed that the development version does resolve your problem.

We're hoping to make another release soon. It would have been this week, but has been delayed by some mysterious JAX/Flax SIGABRT errors in some of our example scripts. It's worth pointing out that you can also install the development version locally using `pip install git+https://github.com/lanl/scico`.

**Comment by DavidNovikov** [comment] 2024-09-19 16:15
installing the development version worked for me, thank you!

**Comment by bwohlberg** [comment] 2024-09-19 20:16
Thanks for confirming. I will close this issue for now, but feel free to re-open it if necessary.

**Closed by bwohlberg** 2024-09-19 20:16 UTC
Labels: examples, question, packaging
